# Generated by Django 3.0.7 on 2020-06-28 09:40

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='image',
            field=models.ImageField(upload_to='images/trades/', validators=[community.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/userpfp/', validators=[community.models.validate_image]),
        ),
    ]
